const ADD_CONTACT = 'ADD_CONTTACT';
const REMOVE_CONTACT = 'REMOVE_CONTACT';
const CHANGE_INPUT_NAME = 'CHANGE_INPUT_NAME';
const CHANGE_INPUT_PHONE = 'CHANGE_INPUT_PHONE';
const CHANGE_ERROR_NAME = 'CHANGE_ERROR_NAME';
const CHANGE_ERROR_PHONE = 'CHANGE_ERROR_PHONE';

export {ADD_CONTACT, REMOVE_CONTACT, CHANGE_INPUT_NAME, CHANGE_INPUT_PHONE, CHANGE_ERROR_NAME, CHANGE_ERROR_PHONE};